name: Graphical_Shop
author: Staartvin
website: http://dev.bukkit.org/bukkit-plugins/graphical-shop/
main: me.staartvin.plugins.graphicalshop.GraphicalShop
version: ${project.version}
description: Allow players to buy and sell items via a handy graphical interface.
permissions:
    graphicalshop.buy:
        description: Allows a player to buy items
        default: op
    graphicalshop.sell:
        description: Allows a player to sell items
        default: op
    graphicalshop.shop:
        description: Allows a player to open the main shop menu.
        default: op
    graphicalshop.reload:
        description: Allows a player to reload Graphical Shop.
        default: op
    graphicalshop.help:
        description: Allows a player to view the help pages
        default: op
    graphicalshop.menus:
        description: Allows a player to view a list of available menus
        default: op    
commands:
    graphicalshop:
      description: Main command of Graphical Shop.
      usage: /gs <arguments>
      aliases: [gs]